# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='topic.proto',
  package='kittens.topic',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btopic.proto\x12\rkittens.topic\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\tTopicList\x12\x0e\n\x06topics\x18\x01 \x03(\t\"\x1c\n\x0cTopicRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2\x89\x01\n\x06Topics\x12=\n\tAllTopics\x12\x16.google.protobuf.Empty\x1a\x18.kittens.topic.TopicList\x12@\n\x07Related\x12\x1b.kittens.topic.TopicRequest\x1a\x18.kittens.topic.TopicListb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TOPICLIST = _descriptor.Descriptor(
  name='TopicList',
  full_name='kittens.topic.TopicList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='kittens.topic.TopicList.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=86,
)


_TOPICREQUEST = _descriptor.Descriptor(
  name='TopicRequest',
  full_name='kittens.topic.TopicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kittens.topic.TopicRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['TopicList'] = _TOPICLIST
DESCRIPTOR.message_types_by_name['TopicRequest'] = _TOPICREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicList = _reflection.GeneratedProtocolMessageType('TopicList', (_message.Message,), dict(
  DESCRIPTOR = _TOPICLIST,
  __module__ = 'topic_pb2'
  # @@protoc_insertion_point(class_scope:kittens.topic.TopicList)
  ))
_sym_db.RegisterMessage(TopicList)

TopicRequest = _reflection.GeneratedProtocolMessageType('TopicRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOPICREQUEST,
  __module__ = 'topic_pb2'
  # @@protoc_insertion_point(class_scope:kittens.topic.TopicRequest)
  ))
_sym_db.RegisterMessage(TopicRequest)



_TOPICS = _descriptor.ServiceDescriptor(
  name='Topics',
  full_name='kittens.topic.Topics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='AllTopics',
    full_name='kittens.topic.Topics.AllTopics',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TOPICLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Related',
    full_name='kittens.topic.Topics.Related',
    index=1,
    containing_service=None,
    input_type=_TOPICREQUEST,
    output_type=_TOPICLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPICS)

DESCRIPTOR.services_by_name['Topics'] = _TOPICS

# @@protoc_insertion_point(module_scope)
